# Generated by Django 3.2.2 on 2021-05-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasketsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
