# Generated by Django 3.2.2 on 2021-05-19 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasketsApp', '0005_auto_20210518_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='basket',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='BasketsApp.basket'),
        ),
    ]
