# Generated by Django 3.2.2 on 2021-05-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasketsApp', '0006_alter_product_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='summarized',
            field=models.BooleanField(default=False),
        ),
    ]
